version: "3"

services:

  spring:
    build:
      context: ./
      args:
        - JAR_FILE=./build/libs/ilvolo-1.0.0.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ilvolo
    depends_on:
      - db

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ilvolo